language: php
php:
    - 5.6
    - 7.0
    - 7.1
    - hhvm

sudo: false

install:
    - travis_retry composer update && composer install --no-interaction --prefer-source

script:
    - vendor/bin/phpunit --verbose --coverage-text --coverage-clover=coverage.xml ./tests

before_install:
    - pip install --user codecov

after_success:
    - bash <(curl -s https://codecov.io/bash)